# Generated by Django 2.2.5 on 2021-11-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirdDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_name', models.CharField(blank=True, max_length=30)),
                ('date_seen', models.DateField(blank=True)),
                ('habitat', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('image', models.TextField(blank=True)),
            ],
        ),
    ]
